apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default "foodhub-dev" }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          
          envFrom:
            - configMapRef:
                name: global-configs
            - secretRef:
                name: foodhub-secrets

          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}

          # --- TỐI ƯU Health Check ---
          readinessProbe:
            httpGet:
              # Nếu là frontend, Values.probePath sẽ là "/" 
              # Nếu là backend, mặc định dùng "/actuator/health/readiness"
              path: {{ .Values.probePath | default "/actuator/health/readiness" }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessDelay | default 60 }} # Tăng lên để chờ tạo DB
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath | default "/actuator/health/liveness" }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessDelay | default 80 }} # Chờ lâu hơn một chút
            periodSeconds: 15

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
