# 1. SERVICE ACTIVE (Bản đang chạy ổn định)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default "foodhub-dev" }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}

---
# 2. SERVICE PREVIEW (Bản mới dùng để test - Green)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview
  namespace: {{ .Values.namespace | default "foodhub-dev" }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP # Preview service luôn là ClusterIP nội bộ
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}