apiVersion: v1
kind: Service
metadata:
  # .Release.Name sẽ tự động lấy tên từ file values (frontend, users, orders...)
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default "foodhub-dev" }}
  labels:
    app: {{ .Release.Name }}
spec:
  # Mặc định là ClusterIP (nội bộ), trừ Frontend sẽ được ghi đè là LoadBalancer trong values
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    - name: http
      # Port mà các service khác sẽ gọi tới (ví dụ: http://users-service:8082)
      port: {{ .Values.servicePort | default .Values.containerPort }}
      # Port thực tế mà ứng dụng trong Container đang lắng nghe
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    # Selector phải khớp với labels trong file deployment.yaml
    app: {{ .Release.Name }}
