replicaCount: 1
containerPort: 3000
serviceType: LoadBalancer 
servicePort: 80

# --- BỔ SUNG: Health Check cho Frontend ---
probePath: "/"              # Sửa lỗi 404 vì Frontend không có actuator
readinessDelay: 15          # Thời gian chờ khởi động nhanh
livenessDelay: 30

image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-frontend
  tag: 821bd1f

env:
  - name: NODE_ENV
    value: "production"
  - name: USERS_SERVICE_URL
    value: "http://users-service:8082"
  - name: PRODUCTS_SERVICE_URL
    value: "http://products-service:8081"
  - name: ORDERS_SERVICE_URL
    value: "http://orders-service:8083"
