replicaCount: 1
containerPort: 8083
image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-orders
  tag: 638097d

env:
  - name: DB_USER
    value: "user_orders"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: foodhub-secrets
        key: DB_PASSWORD_ORDERS
