replicaCount: 1
containerPort: 8081
image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-products
  tag: fd20745

env:
  - name: DB_USER
    value: "user_products"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: foodhub-secrets
        key: DB_PASSWORD_PRODUCTS
