replicaCount: 1
containerPort: 8082
image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-users
  tag: fd20745

env:
  - name: DB_USER
    value: "user_users"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: foodhub-secrets
        key: DB_PASSWORD_USERS
