# Default values for foodhub-chart.

# Số lượng bản sao mặc định
replicaCount: 1

# Cấu hình Image mặc định (Sẽ bị ghi đè bởi từng service)
image:
  repository: "" # Để trống vì mỗi service có ECR riêng
  tag: "latest"
  pullPolicy: Always

# Cổng mặc định của container (ví dụ backend là 8080)
containerPort: 8080

# Loại Service mặc định (Nội bộ)
serviceType: ClusterIP
# servicePort: 80 # Có thể bỏ qua nếu muốn dùng containerPort làm servicePort

# Tài nguyên mặc định (Để EKS không bị quá tải)
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Namespace triển khai
namespace: foodhub-dev

# Biến môi trường mặc định (thường để trống, sẽ khai báo riêng trong từng service-values)
env: []

# Cấu hình Ingress (Mặc định tắt vì bạn đang dùng LoadBalancer cho Frontend)
ingress:
  enabled: false
