apiVersion: v2
name: foodhub-chart
description: Base Helm chart cho Microservices FoodHub (Hỗ trợ Argo Rollouts Blue/Green)
type: application
version: 0.2.0
appVersion: "1.0.0"
maintainers:
  - name: FoodHub-DevOps-Team
    email: admin@foodhub.com
keywords:
  - foodhub
  - microservices
  - eks
  - argo-rollouts