# --- CẤU HÌNH CƠ BẢN ---
replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

# Cổng mặc định của container (Backend thường là 8080)
containerPort: 8080

# Namespace mặc định (Có thể bị ghi đè bởi ArgoCD Application)
namespace: foodhub-dev

# --- CẤU HÌNH BLUE/GREEN (ARGO ROLLOUTS) ---
blueGreen:
  enabled: true
  autoPromotionEnabled: false # Tắt tự động để Demo thủ công (Set true cho Prod thực tế)

# --- CẤU HÌNH SERVICE ---
service:
  type: ClusterIP
  port: 80 # Port mà Service mở ra cho bên ngoài gọi vào

# --- CẤU HÌNH HEALTH CHECK (Logic cũ của bạn) ---
probePath: "/actuator/health/readiness" # Mặc định cho Backend Spring Boot
readinessDelay: 60                      # Chờ DB khởi tạo
livenessDelay: 80

# --- TÀI NGUYÊN ---
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# --- AUTO SCALING (HPA) ---
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# --- INGRESS (Tên miền) ---
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

# --- BIẾN MÔI TRƯỜNG RIÊNG ---
env: []