# Default values for foodhub-chart.

# Số lượng bản sao mặc định
replicaCount: 1

# Cấu hình Image mặc định
image:
  repository: "" 
  tag: "latest"
  pullPolicy: Always

# Cổng mặc định của container
containerPort: 8080

# --- BỔ SUNG: Cấu hình mặc định cho Health Check ---
# Đường dẫn kiểm tra sức khỏe (Mặc định cho Backend)
probePath: "/actuator/health/readiness" 

# Thời gian chờ khởi động (Mặc định cho Backend cần tạo DB)
readinessDelay: 60
livenessDelay: 80

# Loại Service mặc định
serviceType: ClusterIP

# Tài nguyên mặc định
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Namespace triển khai
namespace: foodhub-dev

# Biến môi trường mặc định
env: []

# Cấu hình Ingress
ingress:
  enabled: false
