# --- CẤU HÌNH CƠ BẢN ---
replicaCount: 1
image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-orders
  tag: f087607

containerPort: 8083

# --- BLUE/GREEN ---
blueGreen:
  enabled: true
  autoPromotionEnabled: false

# --- SERVICE ---
service:
  type: ClusterIP
  port: 8083

# --- HEALTH CHECK ---
probePath: "/actuator/health/readiness"
readinessDelay: 60
livenessDelay: 80

# --- BIẾN MÔI TRƯỜNG RIÊNG ---
env:
  - name: DB_USER_ORDERS
    value: "user_orders"
  - name: DB_PASSWORD_ORDERS
    valueFrom:
      secretKeyRef:
        name: foodhub-secrets
        key: DB_PASSWORD_ORDERS