# --- CẤU HÌNH CƠ BẢN ---
replicaCount: 1
image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-products
  tag: "5807155"

containerPort: 8081

# --- BLUE/GREEN ---
blueGreen:
  enabled: true
  autoPromotionEnabled: false

# --- SERVICE ---
service:
  type: ClusterIP
  port: 8081

# --- HEALTH CHECK (Cần chờ Hibernate tạo bảng lâu hơn) ---
probePath: "/actuator/health/readiness"
readinessDelay: 90  # <--- Quan trọng
livenessDelay: 120

# --- BIẾN MÔI TRƯỜNG RIÊNG ---
env:
  - name: DB_USER_PRODUCTS
    value: "user_products" # Lưu ý: tên user này khác format 2 cái kia, giữ nguyên theo code cũ
  - name: DB_PASSWORD_PRODUCTS
    valueFrom:
      secretKeyRef:
        name: foodhub-secrets
        key: DB_PASSWORD_PRODUCTS
